-- SPEC-12: internal CRM
CREATE TABLE IF NOT EXISTS crm_pipelines (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default ENUM('0','1') DEFAULT '0', status ENUM('0','1') DEFAULT '1', created_at DATETIME) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_stages (id INT AUTO_INCREMENT PRIMARY KEY, pipeline_id INT NOT NULL, name VARCHAR(100) NOT NULL, position INT DEFAULT 0, color VARCHAR(7) DEFAULT '#6777ef', stage_type ENUM('open','won','lost') DEFAULT 'open', KEY idx_pipe (pipeline_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_deals (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, pipeline_id INT NOT NULL, stage_id INT NOT NULL, title VARCHAR(150) NOT NULL, value DECIMAL(12,2) DEFAULT 0, currency VARCHAR(10) DEFAULT 'USD', subscriber_id INT NULL, contact_name VARCHAR(120), contact_email VARCHAR(120), contact_phone VARCHAR(40), source ENUM('fb','ig','wa','web','tg','manual') DEFAULT 'manual', ecommerce_cart_id INT NULL, expected_close_date DATE NULL, assigned_to INT NULL, status ENUM('open','won','lost') DEFAULT 'open', lost_reason VARCHAR(255) NULL, won_at DATETIME NULL, created_at DATETIME, updated_at DATETIME, KEY idx_u_p_s (user_id,pipeline_id,stage_id), KEY idx_sub (subscriber_id), KEY idx_status (status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_activities (id INT AUTO_INCREMENT PRIMARY KEY, deal_id INT NULL, subscriber_id INT NULL, user_id INT NOT NULL, type ENUM('call','email','meeting','note','task','follow_up') DEFAULT 'task', subject VARCHAR(150), description TEXT, due_date DATETIME NULL, status ENUM('pending','completed') DEFAULT 'pending', completed_at DATETIME NULL, created_at DATETIME, KEY idx_deal (deal_id), KEY idx_due (user_id,due_date,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_deal_timeline (id INT AUTO_INCREMENT PRIMARY KEY, deal_id INT NOT NULL, user_id INT NOT NULL, action VARCHAR(50), old_value VARCHAR(255), new_value VARCHAR(255), created_at DATETIME, KEY idx_deal (deal_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DELETE FROM menu WHERE url='crm';
INSERT INTO menu (name,icon,color,url,serial,module_access,have_child,only_admin,only_member,add_ons_id,is_external,header_text,is_menu_manager,custom_page_id)
VALUES ('CRM','fas fa-funnel-dollar','#6777ef','crm',7,'',0,0,0,0,0,'',0,0);
